export interface MentalModel {
  name: string;
  category: string;
  description: string;
  promptGuidance: string;
}

export const mentalModels: MentalModel[] = [
  // Core Investment Principles
  {
    name: "Circle of Competence",
    category: "Core Investment",
    description:
      "Know what you know and stay within those boundaries. Acknowledge the edges of your expertise.",
    promptGuidance:
      "Evaluate whether this company operates in an industry/domain that is understandable. Can you predict its business 10 years from now? Are there aspects that require specialized knowledge you don't have?",
  },
  {
    name: "Margin of Safety",
    category: "Core Investment",
    description:
      "Buy at a significant discount to intrinsic value to account for uncertainty and errors in analysis.",
    promptGuidance:
      "Calculate or estimate intrinsic value using DCF, earnings power value, or asset-based methods. Compare to current price. What discount exists? Is it sufficient given the business risk?",
  },
  {
    name: "Mr. Market",
    category: "Core Investment",
    description:
      "The market is a voting machine short-term, weighing machine long-term. Prices can be irrational.",
    promptGuidance:
      "Is the current price driven by fear/greed rather than fundamentals? Has recent price action diverged from intrinsic value changes? Are there opportunities from market irrationality?",
  },
  {
    name: "Intrinsic Value",
    category: "Core Investment",
    description:
      "The present value of all future cash flows that will be generated by a business.",
    promptGuidance:
      "Estimate future cash flows, growth rates, and appropriate discount rate. Use multiple valuation methods. What assumptions are most critical? How sensitive is value to key variables?",
  },

  // Moats & Ownership
  {
    name: "Economic Moats",
    category: "Moats & Ownership",
    description:
      "Sustainable competitive advantages that protect profits: brands, network effects, switching costs, cost advantages, intangible assets.",
    promptGuidance:
      "Identify specific moat sources. How durable are they? Are moats widening or narrowing? What could erode them? Compare to competitors.",
  },
  {
    name: "Owner Earnings",
    category: "Moats & Ownership",
    description:
      "True economic earnings = Net Income + D&A - Maintenance CapEx - Working Capital Changes.",
    promptGuidance:
      "Calculate owner earnings from financial statements. How do they differ from reported earnings? What's the trend? Are earnings being reinvested well?",
  },
  {
    name: "Management Quality",
    category: "Moats & Ownership",
    description:
      "Assess management's capital allocation skills, integrity, and alignment with shareholders.",
    promptGuidance:
      "Evaluate track record of capital allocation. Do they think like owners? Compensation structure? Insider ownership? Communication quality and honesty?",
  },

  // Psychology & Behavioral
  {
    name: "Incentive-Caused Bias",
    category: "Psychology & Behavioral",
    description:
      "People respond to incentives, often unconsciously rationalizing behavior that serves their interests.",
    promptGuidance:
      "What incentives drive management behavior? Analysts? Are there misaligned incentives that could harm shareholders? Who benefits from the current narrative?",
  },
  {
    name: "Social Proof",
    category: "Psychology & Behavioral",
    description:
      "Tendency to follow the crowd, assuming others' actions reflect correct behavior.",
    promptGuidance:
      "Is institutional ownership driving price? Are investors following the herd? Is this a crowded trade? What does contrarian analysis suggest?",
  },
  {
    name: "Availability Bias",
    category: "Psychology & Behavioral",
    description:
      "Overweighting information that comes easily to mind, often recent or vivid events.",
    promptGuidance:
      "Are recent events (good or bad) being overweighted in valuation? What longer-term factors might be overlooked? Is the current narrative too focused on recent performance?",
  },
  {
    name: "Confirmation Bias",
    category: "Psychology & Behavioral",
    description:
      "Seeking information that confirms existing beliefs while ignoring contradictory evidence.",
    promptGuidance:
      "Actively seek disconfirming evidence. What would make this investment fail? What are the strongest bear arguments? What are you potentially missing?",
  },
  {
    name: "Commitment & Consistency",
    category: "Psychology & Behavioral",
    description:
      "Once committed to a position, people tend to stick with it regardless of new information.",
    promptGuidance:
      "Would you buy at current prices if you didn't already own it? Are you anchored to your purchase price? Have circumstances changed since initial thesis?",
  },
  {
    name: "Loss Aversion",
    category: "Psychology & Behavioral",
    description:
      "Losses hurt roughly twice as much as equivalent gains feel good.",
    promptGuidance:
      "Is fear of loss causing you to hold losers too long or sell winners too early? Are you avoiding this stock due to fear rather than analysis?",
  },

  // Lollapalooza Effects
  {
    name: "Lollapalooza Effects",
    category: "Lollapalooza",
    description:
      "Multiple mental models or biases combining to create extreme outcomes.",
    promptGuidance:
      "Identify situations where multiple forces align. Are there compounding positive factors? Or compounding risks? What cascade effects might emerge?",
  },
  {
    name: "Second-Order Thinking",
    category: "Lollapalooza",
    description:
      "Consider not just immediate effects but subsequent consequences: 'And then what?'",
    promptGuidance:
      "Trace through the consequences of key factors. If X happens, then what? What are the second and third order effects of current trends or decisions?",
  },

  // Math & Probability
  {
    name: "Inversion",
    category: "Math & Probability",
    description:
      "Solve problems by thinking backwards. Instead of how to succeed, think about how to fail and avoid that.",
    promptGuidance:
      "What would guarantee this investment fails? What are all the ways to lose money? Avoid those paths. What must NOT happen for thesis to work?",
  },
  {
    name: "Base Rates",
    category: "Math & Probability",
    description:
      "Start with statistical base rates before adjusting for specific circumstances.",
    promptGuidance:
      "What's the base rate of success for companies in this situation? IPOs? Turnarounds? High-growth tech? Start from the outside view before adjusting.",
  },
  {
    name: "Expected Value",
    category: "Math & Probability",
    description:
      "Probability-weighted outcomes. EV = Σ(probability × outcome).",
    promptGuidance:
      "Map out scenarios with probabilities and outcomes. What's the expected value? Is the upside/downside asymmetric? Kelly criterion considerations?",
  },
  {
    name: "Compound Interest",
    category: "Math & Probability",
    description:
      "Exponential growth over time. Small differences in rate matter enormously over long periods.",
    promptGuidance:
      "What's the sustainable earnings growth rate? How long can it compound? What's the ROIC trajectory? Small changes in assumptions compound dramatically.",
  },

  // Economics & Business
  {
    name: "Opportunity Cost",
    category: "Economics & Business",
    description:
      "Every choice means giving up alternatives. Always compare to next best option.",
    promptGuidance:
      "What else could you invest in? How does this compare to your hurdle rate? To an index fund? Are there better opportunities for the same risk?",
  },
  {
    name: "Sunk Cost Fallacy",
    category: "Economics & Business",
    description:
      "Past costs should not influence future decisions. Only future costs and benefits matter.",
    promptGuidance:
      "Ignore your cost basis. Would you buy at today's price? Is the company throwing good money after bad on failing projects?",
  },
  {
    name: "Competitive Destruction",
    category: "Economics & Business",
    description:
      "Competition erodes profits. Industries with easy entry see margins compress to commodity levels.",
    promptGuidance:
      "What prevents competitors from entering? Is the industry consolidating or fragmenting? What's happening to industry margins over time?",
  },
  {
    name: "Scarcity",
    category: "Economics & Business",
    description:
      "Value increases with scarcity. Limited supply of desired goods commands premium.",
    promptGuidance:
      "Does the company control scarce resources? Unique assets? Limited licenses? Irreplaceable relationships? How sustainable is the scarcity?",
  },

  // Systems Thinking
  {
    name: "Feedback Loops",
    category: "Systems Thinking",
    description:
      "Positive feedback amplifies change; negative feedback stabilizes. Identify which loops dominate.",
    promptGuidance:
      "What feedback loops affect the business? Network effects? Economies of scale? Or diminishing returns? Are virtuous or vicious cycles at play?",
  },
  {
    name: "Critical Mass",
    category: "Systems Thinking",
    description:
      "Some systems require minimum scale to function. Network effects need critical user base.",
    promptGuidance:
      "Has the company achieved critical mass? For platforms: is there sufficient network density? Is scale an advantage or has it been reached by competitors?",
  },
  {
    name: "Scale Economics",
    category: "Systems Thinking",
    description:
      "Fixed costs spread over more units reduce per-unit costs. But beware diseconomies of scale.",
    promptGuidance:
      "What's the cost structure? What economies of scale exist? Are there diseconomies emerging? How does unit economics change with scale?",
  },

  // Decision Filters
  {
    name: "Too Hard Pile",
    category: "Decision Filters",
    description:
      "Some investments are too complex or uncertain. Put them in the 'too hard' pile and move on.",
    promptGuidance:
      "Is this analyzable with available information? Are there too many unknowns? Is the future too unpredictable? Sometimes the best decision is to pass.",
  },
  {
    name: "Checklist",
    category: "Decision Filters",
    description:
      "Systematic checklists prevent errors of omission. Pilots use them; investors should too.",
    promptGuidance:
      "Have all key factors been considered? Valuation, moat, management, financial health, risks, catalysts? What might be overlooked?",
  },
];

export function getModelsByCategory(category: string): MentalModel[] {
  return mentalModels.filter((m) => m.category === category);
}

export function getModelByName(name: string): MentalModel | undefined {
  return mentalModels.find((m) => m.name === name);
}
